### PR TITLE
Add scala 2.12 support

### PR DESCRIPTION
**Pull request by a-nigredo**

### CODE REVIEW

**Comment by mielientiev** [comment]
@a-nigredo good work! 
But you need also fix travis in your PR.
Just change `.travis.yml` to:
```
language: scala

scala:
  - 2.11.11
  - 2.12.3

jdk:
  - oraclejdk8
```

That should work

@vitorsvieira  what do you think about this PR? :)

**Comment by vitorsvieira** [comment]
Sure, I'm open for PRs.  👍

**Comment by mielientiev** [comment]
@vitorsvieira great!
I think that @a-nigredo has fixed Travis and now PR has ready to be merged. 
Waiting for release ;)

**Comment by a-nigredo** [comment]
@mielientiev fixed. I'm waiting for release as well since I wanna use dilate in my new project :)

**Comment by mielientiev** [comment]
@vitorsvieira any chance that this PR would be merged and release shortly?

**Comment by vitorsvieira** [comment]
Yes. I will take a look and make the release later today.

**Comment by mielientiev** [comment]
Hi @vitorsvieira, when you can release support of 2.12?

**Comment by vitorsvieira** [comment]
@mielientiev Released 0.1.2. Now, it is just matter of time to appear on maven central.

**Comment by mielientiev** [comment]
@vitorsvieira Thanks!

**Pull request merged**
